import { useState, useEffect } from 'react'
import { useSearchParams } from 'react-router-dom'
import { listReports } from '../../lib/api'
import { onNotification } from '../../lib/signalr'
import type { ExecutiveReport as ExecutiveReportType } from '../../lib/types'
import { ExecutiveReport } from '../../components/ExecutiveReport/ExecutiveReport'

export function Reports() {
  const [searchParams] = useSearchParams()
  const taskId = searchParams.get('taskId')

  const [reports, setReports] = useState<ExecutiveReportType[]>([])
  const [loading, setLoading] = useState(!!taskId)

  // Fetch existing reports on mount when taskId is provided
  useEffect(() => {
    if (!taskId) return
    setLoading(true)
    listReports(taskId)
      .then(data => {
        setReports(data.map(r => ({
          id: r.id,
          agentId: r.agentId,
          agentName: r.agentName,
          title: r.title,
          content: r.content,
          generatedAt: r.generatedAt,
        })))
      })
      .catch(() => {/* degrades gracefully — new reports still arrive via SignalR */})
      .finally(() => setLoading(false))
  }, [taskId])

  // Append new reports as they arrive via SignalR
  useEffect(() => {
    return onNotification(n => {
      if (n.kind === 'executive_report') {
        const m = n.metadata
        const report: ExecutiveReportType = {
          id: m.id as string,
          agentId: m.agentId as string,
          agentName: m.agentName as string,
          title: m.title as string,
          content: m.content as string,
          generatedAt: m.generatedAt as string,
        }
        setReports(prev => {
          if (prev.some(r => r.id === report.id)) return prev
          return [report, ...prev]
        })
      }
    })
  }, [])

  return (
    <div style={styles.root}>
      <h1 style={styles.heading}>Executive Reports</h1>
      <p style={styles.intro}>
        Structured reports generated by executive agents — decisions, actions, and delegations.
        New reports appear here in real time.
      </p>

      {loading ? (
        <div style={styles.empty}>Loading reports…</div>
      ) : reports.length === 0 ? (
        <div style={styles.empty}>
          No reports yet. Reports appear here as agents complete their work.
        </div>
      ) : (
        <div style={styles.list}>
          {reports.map(report => (
            <ExecutiveReport key={report.id} report={report} />
          ))}
        </div>
      )}
    </div>
  )
}

const styles = {
  root: { maxWidth: 720, fontFamily: 'system-ui, sans-serif' },
  heading: { fontSize: 20, fontWeight: 700, color: '#f1f5f9', marginBottom: 8 },
  intro: { fontSize: 14, color: '#94a3b8', marginBottom: 28, lineHeight: 1.6 },
  list: { display: 'flex', flexDirection: 'column' as const, gap: 16 },
  empty: { color: '#475569', fontSize: 14, padding: '2rem 0', textAlign: 'center' as const },
}
